---
title: "Compile_Model"
author: "NMS"
date: '2024-03-06'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(cmdstanr)

# Load the newly installed version of 'rlang'
#library(rlang)
```

```{r}


## Create the data. N.B. note the two variables have different lengths: 1 for n, n for h.
data_try <- list(
  trials = results_df$Trial,  # n of trials
  choice = results_df$RL_Choice,
  feedback = feedback_df$Cumulative_Feedback
)
```


```{r}
## Specify where the model is
file <- file.path("model_RL.stan")

# Compile the model
mod <- cmdstan_model(file, 
                     # this specifies we can parallelize the gradient estimations on multiple cores
                     cpp_options = list(stan_threads = TRUE), 
                     # this is a trick to make it faster
                     stanc_options = list("O1")) 

# The following command calls Stan with specific options.
samples <- mod$sample(
  data = data_try, # the data :-)
  seed = 123,  # a seed, so I always get the same results
  chains = 2,  # how many chains should I fit (to check whether they give the same results)
  parallel_chains = 2, # how many of the chains can be run in parallel?
  threads_per_chain = 2, # distribute gradient estimations within chain across multiple cores
  iter_warmup = 1000,  # warmup iterations through which hyperparameters (steps and step length) are adjusted
  iter_sampling = 2000, # total number of iterations
  refresh = 0,  # how often to show that iterations have been run
  #output_dir = "ACM_Portfolio2", # saves the samples as csv so it can be later loaded
  max_treedepth = 20, # how many steps in the future to check to avoid u-turns
  adapt_delta = 0.99, # how high a learning rate to adjust hyperparameters during warmup
)

# Same the fitted model
samples$save_object("RL_model.rds")
```
Thoughts: The model cant retrieve the fit, because the chains don't finish.
Stan wants a list. The list's parameters need to match the names in the .stan file 